"use client";

// import type { Metadata } from 'next';
import AppTheme from './_shared-theme/AppTheme';
import CssBaseline from '@mui/material/CssBaseline';


// export const metadata: Metadata = {
//   title: "Checkout | Negromart",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/favicon.png",
//   }
// };


export default function CheckoutLayout({ children }: { children: React.ReactNode }, props: { disableCustomTheme?: boolean }) {
  return (
    <AppTheme {...props}>
      <CssBaseline enableColorScheme />        
        {children}
    </AppTheme>
  );
}
