
import '../styles/bootstrap.min.css';
import '../styles/style.css';
import '../styles/demo-3.css';
import '../styles/globals.css';
import Header from '../components/Header';
import Footer from '../components/Footer';

import '../js/main.js';

export const metadata = {
  title: "Home | Negromart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
